version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    timezone: Europe/Amsterdam
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    timezone: Europe/Amsterdam
    interval: "daily"
